src/lib-dev/typography/template.html
У нас был сломан жирный текст в примере, использовался класс, которого не было.
Вот.
=> fix strong text in example

src/lib/public-api.ts
Forget to add progress-spinner module to library export
=> fix(progress-spinner) add module export

src/lib-dev/button/template.html
В пулл реквесте https://github.com/positive-js/mosaic/pull/23 был всего один коммит: https://github.com/positive-js/mosaic/pull/23/commits/04492d0b76f9a35b9f5df546be2a068d452f9316, но он не весь пролез. 
Как минимум это не пролезло.
Убрал дубль из примера и заменил иконку, иначе два дропдауна всех путают.
=> fix button dev examples second try

package-lock.json, package.json, tsconfig.json
Данный реквест порожден различиями работы штатного tslint'а в webstorm'е и его же, но через CLI(с указанием опции --project).
Различия обусловлены https://palantir.github.io/tslint/usage/type-checking/. 
На текущий момент из коробки webstorm это не поддерживает(https://youtrack.jetbrains.com/issue/WEB-22778#), вследствие чего при попытке использовать tslint в webstorm и CLI (с указанием опции --project) получаются разные результаты в части правил с "requires type check".
Для корректной работы данных правил в Webstorm'е подключен плагин `tslint-language-service`
=> chore: added plugin tslint-language-service

src/lib-dev/link/template.html, src/lib/link/_link-theme.scss, src/lib/link/link.component.ts, src/lib/link/link.scss
Заменил стили неактивных ссылок на более удобный и всеми используемый вариант - аттрибут.
=> link disabled style changed to attribute

src/lib/timepicker/timepicker.ts
Код приведён в соответствие с требованиями tslint-config версии 0.10.0
Исключения: оставлены названия свойств, унаследованные от shared интерфейса `HasErrorState` который надо рефакторить везде сразу.
=> bugfix/163532 tslint 0.9.x validity

src/lib/select/select.scss
Тут решается проблема с "вываливанием" текста из матчера.
=> fix(select): Отображение тегов в Match Container (#164347)

src/lib-dev/tabs/module.ts, src/lib-dev/toggle/module.ts, src/lib/tabs/tab-body.ts, src/lib/tabs/tabs.module.ts, src/lib/toggle/toggle.component.spec.ts, src/lib/toggle/toggle.module.ts
- Remove dependency from `BrowserAnimationsModule`
- Change conponents defenition order in `tab-body.ts` according to their dependencies
=> Resolve issue with BrowserAnimationsModule import

src/lib/select/select.html
@Fost 
Проблема: ширина выпадающего списка селекта всегда была равна ширине самого селекта, что не позволяло задавать разную ширину для выпадающего списка и селекта. И в случае, если ширина селекта была auto, то ширина дропдауна была равна ширине селекта, которая могла быть очень мало.
Решение: удалить из шаблона назначение ширины `cdkOverlay`
=> fix(select): fix select overlay autowidth (#172942)

package.json, yarn.lock
There is a vulnerability in karma-junit-reporter package, because its version is old and have lodash package vendor  
https://app.snyk.io/vuln/SNYK-JS-LODASH-73639  
https://app.snyk.io/vuln/npm:lodash:20180130  
https://app.snyk.io/vuln/SNYK-JS-LODASH-73638  
I updated the version of the karma-junit-reporter package. Vulnerability should not be, because karma-junit-reporter package now does not have lodash dependencies.  
Package had version confusion https://github.com/karma-runner/karma-junit-reporter/issues/168  
@Fost  @imrekb
=> chore: updated vendor package karma-junit-reporter to 1.2.0

package.json, yarn.lock
Gulp-dom package has a vulnerability because its version is outdated and has a  jsdom package provider that has a vulnerable package content-type-parse in dependencies  
https://app.snyk.io/vuln/npm:content-type-parser:20170905  
I updated the version of the gulp-dom package. 
@Fost  @imrekb
=> chore: updated vendor package gulp-dom to 1.0.0

package.json, yarn.lock
tslint package has a vulnerability because its version is outdated and has a js-yaml package with a vulnerability  
https://app.snyk.io/vuln/SNYK-JS-JSYAML-173999  
I updated the version of the tslint package. 
@Fost  @imrekb
=> chore: updated vendor package tslint to 5.15.0 version

src/lib/datepicker/datepicker-module.ts
@Fost 
@lskramarov 
@mikeozornin 
RC was about incorrect export\import of McButtonModule
=> fix(issue#110): Datepicker's calendar icon button should be focusable

package.json, yarn.lock
Mosaic had a vulnerability because the scss-bundle package was outdated and had a vulnerability 
https://app.snyk.io/vuln/npm:mem:20180117
I updated version of the scss-bundle package. 
@Fost @imrekb
=> chore: update scss-bundle vendor

src/lib-dev/tooltip/module.ts, src/lib-dev/tooltip/template.html, src/lib/tooltip/tooltip.component.ts, src/lib/tooltip/tooltip.spec.ts
@Fost , @lskramarov please take a look.
Previously I've forgot to call `hide` method in case if mcDisabledTooltip set to false, which trigger changes and set `mcVisible` to false. So the code flow looks like this:
mcTooltipDisabled => set to true => emmit changes => show => ok => mcTooltipDisabled => set to false => emit changes => mcVisible set to false => trigger hide
=> fix(tooltip): Missing hide call when mcDisabled set to true

package.json, yarn.lock
The Gulp-markdown package has a vulnerability because its old version had a vulnerable package marked in dependencies:  
https://app.snyk.io/vuln/SNYK-JS-MARKED-174116
I updated the version of the gulp-markdown package. 
@Fost
=> chore: updated vendor package gulp-markdown to 4.0.0

package.json, yarn.lock
Mosaic had a vulnerability because the karma package was outdated and had a vulnerability package braces  
https://app.snyk.io/vuln/npm:braces:20180219  
I updated version of karma package.  
@Fost
=> chore: update karma vendor

package.json, yarn.lock
Mosaic had vulnerability because @ptsecurity/tslint-config package was outdated and had a vulnerability package tslint:  
https://app.snyk.io/vuln/SNYK-JS-JSYAML-174129  
https://app.snyk.io/vuln/SNYK-JS-JSYAML-173999  
I updated version @ptsecurity/tslint-config package.  
@Fost  @imrekb
=> feat: update-ptsecurity-tslint-config-version

packages/mosaic/list/list-selection.component.spec.ts, packages/mosaic/list/list-selection.component.ts, packages/mosaic/list/list.component.spec.ts, packages/mosaic/list/list.component.ts, packages/mosaic/popover/popover.spec.ts
Кроме самого фикса поправил ошибки линтера в этом компоненте.
=> fix(list): Некорректное выделение в McList (#176613)

packages/mosaic-dev/dateformatter/module.ts, packages/mosaic-moment-adapter/adapter/moment-date-adapter.spec.ts, packages/mosaic-moment-adapter/adapter/moment-date-adapter.ts
@Fost 
@lskramarov 
@mikeozornin 
TFS - 185214
Паста от Мишы
По нашему формату мы не пишем год, когда он текущий. Это приводит к таким картинкам:
http://screenshots.ptsecurity.com/mozornin-2019-06-04_14-11-36.png
Догадаться, что это 2019 невозможно, это небольшая катастрофа. Хочется переработать диапазоны.
Сейчас: Если год текущий на одном из концов, то его не пишем
Надо бы: Если год текущий на обоих концах совпадает, то их оба не пишем.
Примеры здесь: wiki - 20332985 исправлены
=> feat(date-formatter): update range dates formatter to show current year in some cases

packages/mosaic-dev/dateformatter/module.ts, packages/mosaic-dev/select/template.html, packages/mosaic/select/select.component.ts, packages/mosaic/select/select.html, packages/mosaic/select/select.module.ts, packages/mosaic/tree-select/tree-select.component.ts, packages/mosaic/tree-select/tree-select.html
Добавил возможность задавать текст из вне, в те места где этого не было.
Это можно влить.
С остальным нужно определиться.
=> feat(i18n): remove text resources from components

packages/mosaic-dev/tabs/template.html, packages/mosaic/tabs/tab-header.scss
Style for stretch & light tab label has been fixed.
=> Fix(tabs): stretching while applying mc-stretch-tab within mc-light-tab

packages/mosaic/list/list-selection.component.ts
Использовался не тот метод и поэтому не выставлялся previousActiveItemIndex и соответственно выделение работало неправильно.
=> fix(list): Некорректное выделение в mc-list #UIM-15

packages/dev-app/system-config.ts, packages/mosaic/modal/modal.component.html, packages/mosaic/modal/modal.module.ts, tests/karma-system-config.js, tools/packages/rollup-globals.ts
Добавил CdkTrapFocus, теперь фокус из модалки не уходит, но вот изначально его придется инициализировать с помощью autofocus.
В два дефолтных шаблона добавил autofocus.
=> fix(modal): Фокус полей выходит за границы модального окна #UIM-11

packages/mosaic/link/_link-theme.scss, packages/mosaic/link/link.scss
fix(link): add &.cdk-mouse-focused style for correct display of a focused link (#51)
correct display of a focused link on mouth click
Breaking Changes: none
=> fix(link): add style for correct display of a focused link (#51)

packages/mosaic/dropdown/_dropdown-theme.scss
Сейчас у ссылки в компоненте dropdown при фокусе появляется и граница и outline. 
Для решения классу .mc-link добавлено свойство outline: none.
=> fix(dropdown): .mc-link outline set to none #86  

packages/mosaic/select/select.scss
@mikeozornin, проблема была в том, что тегу требуется 28 пикселей, а в select он обрезался родителем в 26px, а потому box-shadow, на который приходится 1px границы обрезался. Я увеличила высоту до 28px и изменила padding .mc-select__trigger - чтобы он укладывался в 30px элемента. А потом убрала  margin-top - он ломал симметрию.
=> fix(multiselect):  multyselect tag size #90

packages/mosaic/core/styles/_alerts.scss, packages/mosaic/radio/_radio-theme.scss, packages/mosaic/radio/radio.component.ts
В компонент radio был добавлен FocusMonitor и отключен фокус при клике мыши. В alert не думаю, что есть смысл добавлять FocusMonitor для кнопки - попробовала установить фокус клавиатурой на реальном alert с `position: absolute;` - не сработало. Пока просто отключила фокус на кнопке закрыть. @mikeozornin, посмотришь?
=> fix(cdk): add cdk-*-focused classes to radio and disable focus on alert #94 

packages/mosaic/dropdown/dropdown.scss
fix(dropdown): dropdown's scroll fix
dropdown's scroll fix
Breaking Changes: none
Проблема была в том, что Edge при первом показе dropdown переносил слова на следующую строку, хотя необходимости в этом не было. На сколько я понимаю, у dropdown потребности в переносе нет, так что пока я поправила баг с помощью `white-space: nowrap;`
=> fix(dropdown): dropdown's scroll fix

packages/docs/src/app/components/anchors/anchors.component.ts, packages/docs/src/app/components/component-viewer/component-overview-theme.scss, packages/docs/src/app/components/component-viewer/component-overview.scss, packages/docs/src/app/components/component-viewer/component-overview.template.html, packages/docs/src/app/components/main-layout/main-layout.component.scss, packages/docs/src/app/docs.scss, packages/docs/src/app/shared/example-viewer/_example-viewer-theme.scss, packages/docs/src/app/shared/example-viewer/example-viewer.html, packages/docs/src/app/shared/example-viewer/example-viewer.scss, packages/docs/src/app/shared/stackblitz/stackblitz-button-theme.scss, packages/docs/src/app/shared/stackblitz/stackblitz-button.html, packages/docs/src/app/shared/stackblitz/stackblitz-button.scss, packages/docs/src/app/shared/stackblitz/stackblitz-button.ts, packages/docs/src/main.scss, packages/docs/src/styles/_common.scss, packages/docs/src/styles/_markdown.scss, packages/mosaic/button/button.md, tools/gulp/tasks/docs.ts
Стилизованы заголовки, текст и ссылки. Не стилизованы: списки и примеры кода.
Добавлен плавный скролл (работает только при поддержке браузера).
=> feat(docs): styling generated from markdown content

packages/mosaic/form-field/form-field.scss
**Whats done**
border-radius applied to all mc-form-field elements.
**Was**
**Now**
**Reviewers**
@Fost @mikeozornin @lskramarov
=> fix(form-field): border radius applied to mc-form-field

packages/docs/src/app/components/footer/footer.component.scss, packages/docs/src/app/shared/doc-viewer/doc-viewer-module.ts, packages/docs/src/app/shared/example-viewer/example-viewer.html, packages/docs/src/app/shared/example-viewer/example-viewer.scss, packages/docs/src/app/shared/example-viewer/example-viewer.ts, packages/docs/src/app/shared/stackblitz/stackblitz-button.scss
Добавлен tooltip при копировании кода из редактора, исправлено заезжание ссылки stackblitz на шапку и области редактора на футер.
=> feat(docs): code editor styling

packages/mosaic/splitter/splitter.component.ts
Непонятно зачем эта логика вообще была добавлена...
=> fix(splitter): sets wrong size for areas (#UIM-110)

404.html, packages/docs/src/app/components/main-layout/main-layout.component.ts
Файл 404.html необходимо поместить в папку https://github.com/positive-js/mosaic-previews
=> feat(docs): 404 routing with localStorage

packages/mosaic/select/select.component.ts, packages/mosaic/select/select.scss, packages/mosaic/tree-select/tree-select.scss
**What's done**
- IE11: fix vertical alignment for select and tree-select components (should be set for inline-block elements with content);
**Was**
**Now**
**Reviewers**
@Fost @mikeozornin @lskramarov
=> fix(form-field): ie fixes: apply vertical alignment on select, tree-select

packages/docs/src/app/components/main-layout/main-layout.component.ts
Сейчас по ссылке https://positive-js.github.io/mosaic-previews/pr140-b19d387/checkbox/overview идет переадресация на button/overview.
Поэтому переадресация  по умолчанию убрана и используется только при отсутствии nextRoute, переданного с 404.html
=> feat(docs): deleting routing to button/overview by default

packages/docs/src/app/components/navbar/_navbar-theme.scss, packages/docs/src/app/components/navbar/navbar.scss, packages/docs/src/app/components/navbar/navbar.template.html
В компоненте навбар ссылки заменены на прозрачные кнопки. В данный момент модификатор _transparent не отрабатывает. PR исправляющий этот баг уже отправлен: https://github.com/positive-js/mosaic/pull/256
=> feat(docs): adding transparent buttons to navbar

packages/mosaic/dropdown/dropdown.scss
В сафари в выпадающем меню любой длины появляется вертикальный скроллбар:
Теперь выпадающее меню в сафари будет выглядеть так:
По каким-то причинам height: 100%; в сафари приводил к появлению вертикального скроллбара. На сколько я понимаю, в классе mc-dropdown__content в этом стиле нет необходимости. Я проверила результат во всех поддерживаемых браузерах: все работает.
Если такая необходимость все же имеется, height: 100% можно заменить на max-height: 100% - с ним тоже все работает.
=> fix(dropdown): hide scrollbar in safary

packages/mosaic/button/_button-theme.scss
Типографика кнопок перенесена из глобальных классов в классы mc-button и mc-icon-button, чтобы она не переопределяла типографику других элементов.
=> fix(button): moving button's typography in specific button's classes

packages/docs/src/app/components/component-viewer/component-overview.template.html, packages/docs/src/app/components/component-viewer/component-viewer.component.ts, packages/docs/src/app/shared/doc-viewer/doc-viewer.ts
Setting fadeOut => fadeIn animation for document name, markdown, and anchors while routing is in process and content isn't rendered yet.
=> feat(docs): setting animation for component-overview

packages/docs/src/app/components/navbar/_navbar-theme.scss, packages/docs/src/app/components/navbar/navbar-property.ts, packages/docs/src/app/components/navbar/navbar.component.ts, packages/docs/src/app/components/navbar/navbar.template.html
INavbarProperty interface and NavbarProperty class are created and moved to separate file. Now, all navbar dropdowns are NavbarProperty objects.
Also selected state is added to version and theme dropdowns.
=> feat(docs): refactoring navbar component

packages/docs/src/app/components/anchors/anchors.scss, packages/docs/src/app/components/component-viewer/component-viewer.component.ts, packages/docs/src/app/components/footer/footer.component.scss, packages/docs/src/app/components/main-layout/main-layout.component.scss, packages/docs/src/app/components/sidenav/sidenav.scss
Уточнено условие начала анимации для предотвращения  ее триггера по изменению якоря.
Уменьшины размеры сайдбара и якорей с 360px до 300px для улучшения адаптивности.
Исправлено перекрытие футером сайдбара, которое нарушало кликабельность нижних пунктов аккордиона.
=> feat(docs): correcting animation's start and adaptivity

packages/docs/src/app/shared/documentation-items/documentation-items.ts, packages/mosaic/core/styles/typography/typography.md, packages/mosaic/icon/icon.md, tools/gulp/tasks/docs.ts
В сайдбар добавлены компоненты с уже существующими md файлами: divider, progress-bar, progress-spinner, и с созданными: icons, typography.
=> feat(docs): adding components description

packages/mosaic/dropdown/dropdown-content.ts, packages/mosaic/dropdown/dropdown-item.ts, packages/mosaic/dropdown/dropdown-panel.ts, packages/mosaic/dropdown/dropdown-trigger.ts, packages/mosaic/dropdown/dropdown.component.ts, packages/mosaic/dropdown/dropdown.html, packages/mosaic/dropdown/dropdown.spec.ts
naming-convention errors are fixed everywhere except interfaces and exported functions.
Private fields are moved after public.
Deprecated event.keyCode is replaced by event.key || event.keyCode because not all browsers support event.key.
Deprecated subscribe(next, error, complete)  is replaced by subscribe(observer).
no-unbounding-method error fixed by binding event.preventDefault with event context.
yarn run server-dev:dropdown workes perfectly.
=> feat(dropdown): fixing tslint errors

packages/mosaic/tabs/tab-body.spec.ts, packages/mosaic/tabs/tab-body.ts, packages/mosaic/tabs/tab-group.ts, packages/mosaic/tabs/tab-header.ts, tslint.json
fixing no-side-effect-code, deprecated, no-inferred-empty-object-type, no-unnecessary-type-assertion, restrict-plus-operands tslint errors.
expect is added to the whitelist for no-unbound-method, because expect doesn't call function, see https://github.com/palantir/tslint/pull/4472 for more details.
=> chore(tabs): fixing tslint errors

packages/docs/src/app/shared/stackblitz/stackblitz-writer.ts, packages/docs/src/assets/stackblitz/styles.css
@ptsecurity/mosaic-icons version is updated in Stackblitz writer.
mc-icons.css is switched to mc-icons-embed.css with embed icon font included.
=> feat(docs): adding embed icon font in Stackblitz examples

packages/docs/src/app/components/component-viewer/component-viewer.component.ts, packages/docs/src/styles/_markdown.scss
Styling blocks of code in markdown, syntax: ```javascript```.
Colors are taken from solarized and Darcula schemes.
Copy icon is added through TS by createCopyIcons function.
Unfortunately, it is not possible to add manually triggering tooltip, so onclick animation is used for UI matter.
=> feat(docs): styling blocks of code in markdown WIP

packages/mosaic/core/option/optgroup.ts, packages/mosaic/core/select/constants.ts, packages/mosaic/core/services/measure-scrollbar.service.ts, packages/mosaic/datepicker/datepicker-input.ts, packages/mosaic/icon/icon.component.ts, packages/mosaic/link/link.component.ts, packages/mosaic/link/link.module.ts, packages/mosaic/list/list-selection.component.spec.ts, packages/mosaic/list/list.module.ts
Fixing naming-convention, ordered-imports, member-ordering, no-empty tslint errors.
Syntax injector.get() is deprecated and now changed to injector.get\<Type\>().
=> chore(common): fixing tslint errors

packages/cdk/tree/control/flat-tree-control.ts
=> feat(tree): added description for getValue and getViewValue, also added compareValues and compareViewValues (#UIM-174)

packages/docs/src/app/components/component-viewer/component-viewer.component.ts, packages/docs/src/app/shared/example-viewer/_example-viewer-theme.scss, packages/docs/src/app/shared/example-viewer/example-viewer.html, packages/docs/src/app/shared/example-viewer/example-viewer.scss, packages/docs/src/app/shared/example-viewer/example-viewer.ts, packages/docs/src/highlightjs/material-dark.scss, packages/docs/src/highlightjs/material-light.scss, packages/docs/src/styles/_markdown.scss
Bringing code copy icon in example viewer and markdown to the same view. Tooltip isn't used anymore.
Now after copying icon switching on text:
=> feat(docs): restyling code copy icon

packages/docs/src/app/components/main-layout/main-layout.component.scss
setting content width to calc(100% - 600px) for empty examples and correct view in Edge
=> feat(docs): setting content width

packages/mosaic/form-field/_form-field-theme.scss
The color of the icon in form-field prefix should be defined by the current theme settings.
=> fix(form-field): change prefix icon color according the theme settings (#UIM-195)

packages/mosaic/checkbox/checkbox.ts, packages/mosaic/dropdown/dropdown-item.ts, packages/mosaic/form-field/form-field.ts, packages/mosaic/input/input.ts, packages/mosaic/list/list-selection.component.ts, packages/mosaic/progress-bar/progress-bar.component.ts, packages/mosaic/progress-spinner/progress-spinner.component.ts, packages/mosaic/radio/radio.component.ts, packages/mosaic/tabs/tab-group.ts, packages/mosaic/tabs/tab-label-wrapper.ts, packages/mosaic/tabs/tab-nav-bar/tab-nav-bar.ts, packages/mosaic/tabs/tab.ts, packages/mosaic/tags/tag-list.component.ts, packages/mosaic/tags/tag.component.ts, packages/mosaic/toggle/toggle.component.ts, packages/mosaic/vertical-navbar/vertical-navbar-item.component.ts
Right now naming-convention is disabled for all such constants. Naming convention should be updated in order to remove tslint:disable-next-line:naming-convention comments
=> chore(common): renaming constants for extends

packages/cdk/datetime/date-adapter.ts, packages/mosaic/input/input.ts, packages/mosaic/modal/modal.component.ts, packages/mosaic/tags/tag-list.component.ts, packages/mosaic/textarea/textarea.component.ts
Setting most of the properties with set and get to private.
Some, like in packages/cdk/tree/padding.ts are keeping as they were to avoid breaking changes.
=> chore(common): setting properties with set and get to private

packages/mosaic/modal/modal.component.html
If a click was started over the modal body (`mousedown`) but was finished outside the body (`mouseup`), modal mask `click` handler was triggered. In order to fix it, the mask's handler type was changed from `click` to `mousedown`, so the click should be started **outside** the modal body to be handled by the mask.
=> fix(modal): change mask click handler to mousedown handler (#UIM-169)

packages/docs/src/app/components/anchors/_anchors-theme.scss, packages/docs/src/app/components/anchors/anchors.component.html, packages/docs/src/app/components/anchors/anchors.component.ts, packages/docs/src/app/components/component-viewer/component-viewer.component.ts
Page title is added to the anchor's menu and is separated by border-bottom. Now adding at least one anchor to page isn't necessary.
Bug of not updating anchors on contentRenderFailed error is fixed.
=> feat(docs): adding page title to anchors

packages/mosaic/modal/_modal-theme.scss, packages/mosaic/modal/modal.component.html, packages/mosaic/modal/modal.scss
The close button had no focus state because it wasn't a `mc-button` instance, therefore it wasn't being watched by the  `FocusMonitor`. I've transformed the button into `mc-button` with transparent background and overrode its wrapper `hover` styles (its background wasn't transparent).
=> fix(modal): setup modal close button focus styles (#UIM-200)

packages/docs/src/styles/_markdown.scss
white-space: pre-line was breaking code's indents, to save them and to keep text's translation to a new line it was switched to white-space: pre-wrap;
=> fix(docs): fixing codes examples  white-space

packages/docs/src/app/components/main-layout/main-layout.component.ts
setNextRoute function was developed to set routing for GitHub due to its 404.html problem. But it was breaking routing for other platforms, so setDefaultRoute function was written for them.
=> fix(docs): fixing routing for not githab platforms

packages/mosaic/tags/tag.scss, tools/webpack/default_index.ejs
не нашел в core-js полифила для remove...
поэтому пока добавил в index через script.
Еще заметил, что packages\mosaic-dev\index.html не используется, а вместо него используется tools\webpack\default_index.ejs - видимо index.html нужно удалить.
=> fix(tags): logic for one more does not work in examples (#UIM-147)

packages/docs/src/app/components/navbar/navbar-property.ts, packages/docs/src/app/components/navbar/navbar.component.ts, packages/docs/src/app/components/navbar/navbar.template.html
Now the selected version is not saving in localStorage. Considering the fact, that version is defined by domain and package.json, the current and selected version is taken with the use of static data array and version from  package.json.
=> feat(docs): setting version from INavbarProperty to custom property

packages/mosaic-dev/modal/module.ts, packages/mosaic/modal/modal-ref.class.ts, packages/mosaic/modal/modal.component.ts
=> feat(modal): add markForCheck for modal (#UIM-262)

packages/mosaic/input/input.ts
Undo and Redo commands weren't "white-listed" in `onKeyDown` event handler and their default behavior was prevented.
=> fix(input): Enable event prevention only for point and arrow keys (#UIM-161)

packages/mosaic-examples/mosaic/card/card-overview/card-overview-example.css, packages/mosaic-examples/mosaic/card/card-overview/card-overview-example.html, packages/mosaic-examples/mosaic/card/card-overview/card-overview-example.ts, packages/mosaic-examples/mosaic/card/module.ts, packages/mosaic-examples/mosaic/splitter/module.ts, packages/mosaic-examples/mosaic/splitter/splitter-fixed/splitter-fixed-example.css, packages/mosaic-examples/mosaic/splitter/splitter-fixed/splitter-fixed-example.html, packages/mosaic-examples/mosaic/splitter/splitter-fixed/splitter-fixed-example.ts, packages/mosaic-examples/mosaic/splitter/splitter-nested/splitter-nested-example.css, packages/mosaic-examples/mosaic/splitter/splitter-nested/splitter-nested-example.html, packages/mosaic-examples/mosaic/splitter/splitter-nested/splitter-nested-example.ts, packages/mosaic-examples/mosaic/splitter/splitter-overview/splitter-overview-example.css, packages/mosaic-examples/mosaic/splitter/splitter-overview/splitter-overview-example.html, packages/mosaic-examples/mosaic/splitter/splitter-overview/splitter-overview-example.ts, packages/mosaic-examples/mosaic/splitter/splitter-vertical/splitter-vertical-example.css, packages/mosaic-examples/mosaic/splitter/splitter-vertical/splitter-vertical-example.html, packages/mosaic-examples/mosaic/splitter/splitter-vertical/splitter-vertical-example.ts, packages/mosaic/card/card.md, packages/mosaic/splitter/splitter.md
Классы flex и layout-column почему то в доках недоступны временно сделал их в самом примере.
=> feat(docs): added examples for card and splitter (#UIM-290)

packages/mosaic-dev/card/styles.scss, packages/mosaic/datepicker/_datepicker-theme.scss, packages/mosaic/popover/popover.scss
Also delete `.mc-upload-to-cloud_24` class styles
=> fix(typography): replace font-size numbers with mixins (#UIM-271)

commitlint.config.js, packages/mosaic-examples/mosaic/list/list-groups/list-groups-example.css, packages/mosaic-examples/mosaic/list/list-groups/list-groups-example.html, packages/mosaic-examples/mosaic/list/list-groups/list-groups-example.ts, packages/mosaic-examples/mosaic/list/module.ts, packages/mosaic-examples/mosaic/select/module.ts, packages/mosaic-examples/mosaic/select/select-groups/select-groups-example.css, packages/mosaic-examples/mosaic/select/select-groups/select-groups-example.html, packages/mosaic-examples/mosaic/select/select-groups/select-groups-example.ts, packages/mosaic/core/option/_optgroup-theme.scss, packages/mosaic/core/option/optgroup.html, packages/mosaic/core/option/optgroup.scss, packages/mosaic/core/option/optgroup.ts, packages/mosaic/core/styles/typography/_all-typography.scss, packages/mosaic/core/theming/_all-theme.scss, packages/mosaic/list/_list-theme.scss, packages/mosaic/list/list-selection.component.ts, packages/mosaic/list/list.md, packages/mosaic/list/list.module.ts, packages/mosaic/list/list.scss, packages/mosaic/select/select.component.spec.ts, packages/mosaic/select/select.md
@mikeozornin пример сразу добавлен в документацию, можно локально собрать и посмотреть.
=> feat(optgroup): added optgroup in select and list (#UIM-318)

packages/docs/src/assets/stackblitz/mosaic-module.ts, packages/mosaic-examples/mosaic/modal/modal-component/modal-component-example.css, packages/mosaic-examples/mosaic/modal/modal-component/modal-component-example.html, packages/mosaic-examples/mosaic/modal/modal-component/modal-component-example.ts, packages/mosaic-examples/mosaic/modal/modal-overview/modal-overview-example.css, packages/mosaic-examples/mosaic/modal/modal-overview/modal-overview-example.html, packages/mosaic-examples/mosaic/modal/modal-overview/modal-overview-example.ts, packages/mosaic-examples/mosaic/modal/modal-template/modal-template-example.css, packages/mosaic-examples/mosaic/modal/modal-template/modal-template-example.html, packages/mosaic-examples/mosaic/modal/modal-template/modal-template-example.ts, packages/mosaic-examples/mosaic/modal/module.ts, packages/mosaic/modal/modal.md
Добавлены базовый пример модального окна, пример с шаблонами и пример с кастомным компонентом. В примере с кастомномным компонентом показана передача параметров Input и подписка на события afterOpen и afterClose с передачей параметров из кастомного компонента.
В модуль stackblitz добавлен McProgressSpinnerModule.
=> feat(docs): adding modal examples

packages/docs/src/main.scss
Setting background and color for body so that element, opend out of <docs-app></docs-app> scope, get right background and color to inherit
=> fix(docs): setting background and color for body

packages/mosaic/timepicker/timepicker.spec.ts, packages/mosaic/timepicker/timepicker.ts
=> fix(timepicker): Add value updates after changing the format (#UIM-247)

packages/mosaic/form-field/form-field-errors.ts, packages/mosaic/form-field/form-field.ts, packages/mosaic/input/input.spec.ts
Добавлено исключение на использование mc-cleaner в form-field совместно с numberInput.
=> fix(input): need notify if mc-cleaner used with input that have type=number (#UIM-332)

packages/mosaic/select/select.component.ts, packages/mosaic/tree-select/tree-select.component.ts
Добавил расчет размеров элемента с учетом margins, до этого был хардкод 4px.
Код в select и tree-select дублируется, но это уберем, когда будем рефакторить, там матчер можно вынести в компонент и всю эту логику убрать в него...
=> fix(select, tree-select): "one more" label will hide if open select (#UIM-352)

packages/mosaic/modal/modal.component.ts
Поковырял то что есть и пришел к выводу, что пока проще всего отключить ChangeDetectionStrategy.OnPush в McModalComponent.
@Fost посмотри, возможно Я не совсем понял реализацию и есть другой вариант решения этой проблемы.
=> fix(modal): for apply changes need run changeDetection (#UIM-348)

packages/cdk/a11y/key-manager/focus-key-manager.ts, packages/cdk/a11y/key-manager/list-key-manager.ts, packages/cdk/schematics/ng-add/index.spec.ts, packages/cdk/schematics/ng-add/index.ts, packages/cdk/schematics/testing/test-app.ts, packages/cdk/schematics/utils/build-component.ts, packages/cdk/schematics/utils/parse5-element.ts, packages/cdk/schematics/utils/version-agnostic-typescript.ts, packages/cdk/testing/type-in-element.ts, packages/cdk/tree/padding.ts, packages/cdk/tree/tree._spec.ts, tslint.json
tslint naming-convention, no-unnecessary-type-assertion, member-ordering, deprecation,  no-require-imports, no-for-in rules, magic-numbers are fixed.
deprecated runSchematic function is replaced with runSchematicAsync, and runExternalSchematic with runExternalSchematicAsync.
for in is replaced with Object.keys().forEach()
=> chore(common): cdk tslint fix

packages/mosaic/tags/tag-input.ts, packages/mosaic/tags/tag-list.component.spec.ts
Убрал выставление атрибута aria-invalid, мы все равно их не используем, где то остались после copy/paste...
Странно, что заметили только сейчас, _tagList стал приватным еще в сентябре прошлого года и локальная сборка с флагом AoT тоже пропускает это...
=> fix(input): errors with AoT (#UIM-370)

packages/mosaic/tags/tag-list.component.spec.ts, packages/mosaic/tags/tag-list.scss, packages/wallabyTest.ts
Не учитывался бордер.
Восстановил работоспособность тестов в wallaby.
Добавил пару тестов на проверку высоты.
=> fix(tags): incorrect height (#UIM-365)

.circleci/config.yml, package.json, tools/gulp/tasks/lint.ts, yarn.lock
yaml check job is added to .circleci\config.yml.
Right now yaml lint is done through package.json only. It seems, that because of yaml lint execution file is placed not in bin directory, our usual gulp task('taskName', execNodeTask()) wouldn't work.
Also, thought this package check file for errors, it doesn't really do much linting, just checking that file is valid.
=> build: adding yaml check

packages/docs/src/app/shared/example-viewer/_example-viewer-theme.scss
Copy icon is clickable so cursor must be pointer.
=> fix(docs): copy icon is clickable so cursor: pointer

packages/docs/src/styles/_theme-dark.scss, packages/mosaic-dev/flex-layout/styles.scss, packages/mosaic-dev/splitter/styles.scss, packages/mosaic-dev/tooltip/styles.scss, packages/mosaic-examples/mosaic/datepicker/datepicker-disabled/datepicker-disabled-example.css, packages/mosaic/button-toggle/button-toggle.scss, packages/mosaic/checkbox/_checkbox-theme.scss, packages/mosaic/checkbox/checkbox.scss, packages/mosaic/core/styles/common/_animation.scss, packages/mosaic/form-field/_form-field-theme.scss, packages/mosaic/form-field/form-field.scss, packages/mosaic/link/_link-theme.scss, packages/mosaic/navbar/_navbar-theme.scss, packages/mosaic/progress-spinner/progress-spinner.scss, packages/mosaic/select/select.scss, packages/mosaic/tags/_tag-theme.scss, packages/mosaic/tags/tag-list.scss, packages/mosaic/tree-select/tree-select.scss
Fixing zero before dot, max-length, indent, duplicate, and no-descending-specificity rules.
Due to [stylelint/stylelint#4271](https://github.com/stylelint/stylelint/issues/4271) no-descending-specificity rule ignores parent specificity, so to make our SCSS component-like code valid we need to switch it off when needed
=> chore(common): fixing stylelint

packages/mosaic/datepicker/_datepicker-theme.scss
Disabled button has 0.3 opacity by default, but datepicker toggle button should have full opacity.
=> fix(datepicker): fixing datepicker toggle button opacity (#UIM-396)

packages/mosaic/table/table.scss
Fixing linter:styles:json test for CI
=> chore(common): disabling descending specificity for tables

packages/mosaic/core/theming/_palette.scss, packages/mosaic/radio/_radio-theme.scss
Fixing radio disabled icon color and  basic border color from CCCCCC to B3B3B3
=> fix(radio): fixing disabled form icon's and basic border's colors (#UIM-396)

packages/mosaic-dev/main.scss
Для светлой темы был указан неправильный путь
=> fix(docs): fix light theme in dev docs

packages/mosaic-examples/mosaic/typography/typography-overview/typography-overview-example.css, packages/mosaic-examples/mosaic/typography/typography-overview/typography-overview-example.html
The text of class name made more visible on the dark theme (set for text opacity: 0.5)
=> fix(visual): Maked text of class name more visible on the dark theme

packages/mosaic-dev/popover/module.ts, packages/mosaic-dev/popover/styles.scss, packages/mosaic-dev/popover/template.html, packages/mosaic/core/overlay/overlay-position-map.ts, packages/mosaic/popover/popover.component.ts, packages/mosaic/popover/popover.scss
@Fost please take a look.
Dev example updated.
Add ResizeObserver for monitoring of content resize.
=> fix(popover): positioning and dev-example updates (UIM-447)

packages/mosaic/timepicker/timepicker.ts
@mikeozornin, @Fost 
Исправлена ошибка валидации при пустом поле ввода
Странный валдатор, повторяет логику `requiered`  
Плюс форматом занимается мозаик, у макс и мин валидаторов, присутствует проверка, что таймпикер имеет значение.
=> fix(timepicker): remove parseValidator (#UIM-464)

packages/mosaic/timepicker/timepicker.ts
@mikeozornin, @Fost 
Исправлена ошибка валидации при пустом поле ввода  
[Решение для 8.5.x](https://github.com/positive-js/mosaic/pull/476)
=> fix(timepicker): parseValidator check for empty (#UIM-464)

.circleci/config.yml, sonar-project.properties
Задачи с аудитом безопасности запускаются теперь только от команды (из-за обеспечения безопасного доступа к переменным окружения)
https://circleci.com/docs/2.0/contexts/#restricting-a-context
=> chore: separate security audit (#451)

packages/mosaic/button/_button-theme.scss
Fix buttons focus border in dark mode (UIM-488)
=> fix(button): correct focus border for buttons in dark theme

.snyk, package.json, yarn.lock
Обновление вендора karma на новую версию, которое повлекло фикс следующих уязвимостей:  
1)  https://app.snyk.io/vuln/SNYK-JS-USERAGENT-174737 - mosaic@9.1.4 › karma@4.4.1 › useragent@2.3.0.  
2) https://app.snyk.io/vuln/SNYK-JS-HTTPPROXY-569139 - mosaic@9.1.4 › karma@4.4.1 › http-proxy@1.18.0.  
3) mosaic@9.1.4 › karma@4.4.1 › optimist@0.6.1 › minimist@0.0.10.  
* Karma plugins which rely on the fact that Karma uses Bluebird promises may break as Bluebird-specific API is no longer available on Promises returned by the Karma core
* **server:** Deprecated createPreprocessor removed, karma-browserify < 7 version doesn't work
* no more testing on node 8.
@imrekb
=> chore: update vendor karma

packages/mosaic-dev/tooltip/template.html, packages/mosaic/tooltip/tooltip.component.ts, packages/mosaic/tooltip/tooltip.scss
There is an issue with this pr. When the height of tooltip is bigger than the height of the host element it looks quiet bad. This happens because the positioning of the arrow is [hardcoded at the moment](https://github.com/positive-js/mosaic/blob/a5e64ffb54aea3e8136fedc18ecb2d4bc63d939f/packages/mosaic/tooltip/tooltip.scss#L71).
=> fix: updated positioning logic in tooltips (#UIM-511)

packages/mosaic-examples/mosaic/tags/tags-autocomplete/tags-autocomplete-example.html, packages/mosaic-examples/mosaic/tags/tags-autocomplete/tags-autocomplete-example.ts
Как оказалось это из-за создания тега по onBlur и ранее в дев пример был добавлен способ для обхода подобного поведения.
В итоге поправил пример в доках, но из-за невозможности собрать и запустить документацию не смог проверить.
=> fix(docs): Autocomplete with active search - selection incorrect (#UIM-518)

packages/mosaic/datepicker/_datepicker-theme.scss
В стилях календаря используется стили body для line-height и при определении типографики в проекте верстка ломается.
=> fix(datepicker): Line-height changes (#UIM-399)

packages/mosaic-dev/modal/module.ts, packages/mosaic-dev/modal/template.html, packages/mosaic/modal/modal.component.html, packages/mosaic/modal/modal.component.ts, packages/mosaic/modal/modal.directive.ts, packages/mosaic/modal/modal.module.ts, packages/mosaic/modal/modal.spec.ts, packages/mosaic/modal/modal.type.ts
Добавлено выполнение основного действия модального окна по Ctrl+Enter.
Основное действие — primary- или единственная кнопка в футере. Если нет футера, то действие «Закрыть».
Также при открытии модального окна добавлен фокус на primary- или первой кнопке в футере. Если футера нет, то на первой найденной кнопке (Крестик)
Фокус на модальном окне необходим, чтобы срабатывало действие по Ctrl+Enter
=> feat(modal): implementation by guideline hotkey ctrl+enter (#UIM-441)

packages/mosaic/autocomplete/autocomplete-trigger.directive.ts, packages/mosaic/autocomplete/autocomplete.spec.ts
Автоматическое выделение первого `disabled` элемента автокомплита при его открытии исправлено на выделение первого активного элемента, если хоть один такой есть в списке. Если в списке нет активных элементов, то ничего не выделяется. 
Добавил два теста и новую фикстуру для них. Проверил, что остальные тесты автокомплита не падают.
=> fix(autocomplete): disabled items should not be auto activated (#UIM-615)

packages/mosaic/autocomplete/autocomplete-trigger.directive.ts, packages/mosaic/autocomplete/autocomplete.component.ts, packages/mosaic/autocomplete/autocomplete.spec.ts
Добавлен атрибут `autoOpenOnFocus`, который управляет автоматическим открытием выпадающего списка автокомплита при фокусе в поле ввода. Значение по умолчанию `true`. 
Добавил два теста и новую фикстуру для проверки нового атрибута. Добавил тест для существующей фикстуры без атрибута для проверки работы по умолчанию.
=> feat(autocomplete): Added ability to not show dropdown on focus (#UIM-616)

packages/mosaic-luxon-adapter/adapter/date-adapter.spec.ts, packages/mosaic-luxon-adapter/adapter/locales/en-US.ts, packages/mosaic-luxon-adapter/adapter/locales/ru-RU.ts, packages/mosaic-moment-adapter/adapter/moment-date-adapter.spec.ts, packages/mosaic/core/formatters/date/templates/en-US.ts, packages/mosaic/core/formatters/date/templates/ru-RU.ts
Оказалось, что с опцией `milliseconds: true` не отображались секунды, в шаблоне их просто не было.
=> fix(mosaic-luxon-adapter): absoluteLongDateTime and absoluteShortDateTime without seconds (#UIM-666)

packages/mosaic/list/_list-theme.scss
Стиль для mc-list-option потерялся при переходе на [токены](https://github.com/positive-js/mosaic/commit/7438db4991124b2a869aa38bdc0f1f77e6c74d25#diff-4ea7cabd5b93cb165d032ee0f52544f929891d6b5e38052231704b3ea7460693R38).
Из-за этого размер шрифта наследовался от родительских элементов.
=> fix(list): List option font size (#UIM-658)

packages/mosaic/dropdown/dropdown-trigger.ts, packages/mosaic/dropdown/dropdown.spec.ts
Исправлены следующие проблемы:
- дропдаун нельзя закрыть по клику на элемент-тригер;
- при клике на элемент-тригер с открытым дропдауном, новый дропдаун отрисовывается справа от не успевшего закрыться предыдущего.
Для решения прблем сброс состояния дропдауна теперь происходит после завершения анимации дропдауна (в нашем случае это анимация закрытия)
=> fix(dropdown): Fixed issues with closing and flashing of dropdown by second click (#UIM-664)

packages/mosaic-moment-adapter/adapter/locales/en-US.ts, packages/mosaic-moment-adapter/adapter/locales/ru-RU.ts, packages/mosaic-moment-adapter/adapter/moment-date-adapter.spec.ts
=> fix(mosaic-moment-adapter): fixed formats for seconds and minutes and added tests for it (#UIM-689)

tools/gulp/tasks/docs.ts, tools/highlight-files/highlight-code-block.ts
https://youtrack.ptsecurity.com/issue/UIM-627
убрал варнинги
=> fix(highlight): fixed highlight.js deprecation warning (UIM-627)

packages/mosaic/list/list-selection.component.ts
в методе setSelectedOptionsByKey() эмитился selectionChange при любом нажатии, если список в режиме autoSelect.
сделал, чтобы эмитилось только при нажатии на кнопки для вертикального движения
=> fix(list): restrict keyDown event (#UIM-804)

packages/mosaic/list/list-selection.component.ts
Исправлена ошибка, появляющаяся при размещении mc-list-selection внутри mc-dropdown.
Пример https://stackblitz.com/edit/angular-uqagk9?file=app%2Fdropdown-overview-example.html
Открыть и закрыть дропдаун, потом поменять размер окна браузера.
=> fix(list): Error in getHeight after window resize (#UIM-581)

packages/mosaic/timepicker/timepicker.directive.ts
Метод onInput() вызывается в onBlur() и в onKeyDown(). 
Из-за этого ngModelChange эмитил 2 раза при нажатии tab.
Поэтому добавил TAB в if с noop() в onKeyDown()
=> fix(timepicker): ngModelChange emitted twice on tab key (#UIM-784)

packages/mosaic/select/select.component.ts
Перенесено исправление отсюда https://github.com/positive-js/mosaic/pull/517/files
=> fix(select): select with search doesn't let type a space (#UIM-817)

packages/mosaic/button/button.scss
на скрине до и после добавления align-items: center
=> fix(button): add align center (#UIM-790)

packages/mosaic/timepicker/timepicker.directive.ts, packages/mosaic/timepicker/timepicker.spec.ts
При генерации даты из введённого времени, не обрабатывался случай когда текущее значение null
=> fix(timepicker): fix for error when formControl has null value (#UIM-729)

packages/mosaic/button/_button-theme.scss
[Прозрачная кнопка ломает иконку из пакета pt-flag-icons](https://youtrack.ptsecurity.com/issue/UIM-776)
=> fix(modal): btn transparent bgcolor (#UIM-776)

packages/mosaic/modal/modal.component.html, packages/mosaic/modal/modal.service.ts, packages/mosaic/modal/modal.spec.ts
[Bug UIM-750  modalService.create без footerRef создаёт лишний футер](https://youtrack.ptsecurity.com/issue/UIM-750)
Добавлена проверка на наличие mcFooter, mcOkText, mcCancelText, если данных опций не будет - футер не будет выводиться
=> fix(modal): footer of modal (#UIM-750)

packages/mosaic-dev/popover/module.ts, packages/mosaic-dev/popover/template.html, packages/mosaic-examples/mosaic/popover/popover-overview/popover-overview-example.html, packages/mosaic/popover/popover-confirm.component.html, packages/mosaic/popover/popover.component.html, packages/mosaic/popover/popover.component.ts, packages/mosaic/popover/popover.module.ts
[[UI] It should be possible to set focus trap for popover](https://youtrack.ptsecurity.com/issue/UIM-603)
Добавлены cdkTrapFocus и cdkTrapFocusAutoCapture для mc-popover
При trigger = Focus, cdkTrapFocus и cdkTrapFocusAutoCapture надо включить
=> fix(popover): trap focus in popover (#UIM-603)

packages/mosaic/core/pop-up/pop-up-trigger.ts
Задача: https://youtrack.ptsecurity.com/issue/UIM-579
Отступ работает только справа:
http://screenshots.ptsecurity.com/chrome_Spf1DEiLeK.png
http://screenshots.ptsecurity.com/chrome_VYYluqrGrk.png
Может быть его лучше оставить и сделать равным нулю, не нашла конкретно эту ошибку, но похожая - https://github.com/angular/components/issues/23127
=> fix(popover): remove popover viewport margin (#UIM-579)

packages/mosaic-dev/date-formatter/module.ts, packages/mosaic-dev/date-formatter/template.html, packages/mosaic-examples/mosaic/date-formatter/absolute-date-formatter/absolute-date-formatter-example.html, packages/mosaic-examples/mosaic/date-formatter/absolute-date-formatter/absolute-date-formatter-example.ts, packages/mosaic-examples/mosaic/date-formatter/range-date-formatter/range-date-formatter-example.html, packages/mosaic-examples/mosaic/date-formatter/range-date-formatter/range-date-formatter-example.ts, packages/mosaic-examples/mosaic/date-formatter/relative-date-formatter/relative-date-formatter-example.html, packages/mosaic-examples/mosaic/date-formatter/relative-date-formatter/relative-date-formatter-example.ts, packages/mosaic/core/formatters/date/formatter.spec.ts, packages/mosaic/core/formatters/date/formatter.ts, packages/mosaic/core/formatters/date/templates/en-US.ts, packages/mosaic/core/formatters/date/templates/ru-RU.ts, tools/public_api_guard/mosaic/core.api.md
@lskramarov Добавил объект options с seconds и milliseconds в аргументы всех методов, оканчивающихся на DateTime.
Я думаю, что в доках нет смысла добавлять секунды и миллисекунды во все форматы, получится слишком громоздко.
Лучше сделать снизу отдельный раздел, и в нём написать, что все DateTime методы принимают [DateTimeOptions](https://github.com/positive-js/mosaic/compare/master...oburdasov:feature/UIM-781?expand=1#diff-a9fb7c6ecfea87eedb969444d15d2e96b951828b4ab4bc5228e36658f784eb62R49)
=> feat(formatter): add seconds and milliseconds options (#UIM-781)

packages/mosaic/design-tokens/legacy-2017/tokens/components/table.json5, packages/mosaic/design-tokens/pt-2022/tokens/components/table.json5
В PR где делали табличные стили забыл это изменение. Оно не исправляет все таблицы, но по дефолту так точно будет лучше.
=> feat(table): use tabular styles for body content by default
