positive-js/mosaic

package-lock.json
package.json
src/lib/checkbox/checkbox.scss

Обновлена верси mosaic-icons; Фикс для стилей чекбокса.

fix(checkbox): remove font-size for icons; update mosaic-icons version

---

src/lib/navbar/README.md

feat(navbar): readme added

---

package.json
src/lib-dev/progress-bar/module.ts
src/lib-dev/progress-bar/styles.scss
src/lib-dev/progress-bar/template.html
src/lib/core/theming/_all-theme.scss
src/lib/progress-bar/_progress-bar-theme.scss
src/lib/progress-bar/index.ts
src/lib/progress-bar/progress-bar.component.html
src/lib/progress-bar/progress-bar.component.spec.ts
src/lib/progress-bar/progress-bar.component.ts
src/lib/progress-bar/progress-bar.md
src/lib/progress-bar/progress-bar.module.ts
src/lib/progress-bar/progress-bar.scss
src/lib/progress-bar/public-api.ts
src/lib/progress-bar/tsconfig.build.json
src/lib/public-api.ts
tests/karma-test-shim.js

feat(progress-bar)

---

src/lib/progress-bar/progress-bar.scss

feat(progress-bar) change animation timing function

---

package.json
src/lib-dev/progress-spinner/module.ts
src/lib-dev/progress-spinner/styles.scss
src/lib-dev/progress-spinner/template.html
src/lib/core/theming/_all-theme.scss
src/lib/progress-spinner/_progress-spinner-theme.scss
src/lib/progress-spinner/index.ts
src/lib/progress-spinner/progress-spinner.component.html
src/lib/progress-spinner/progress-spinner.component.spec.ts
src/lib/progress-spinner/progress-spinner.component.ts
src/lib/progress-spinner/progress-spinner.md
src/lib/progress-spinner/progress-spinner.module.ts
src/lib/progress-spinner/progress-spinner.scss
src/lib/progress-spinner/public-api.ts
src/lib/progress-spinner/tsconfig.build.json
tests/karma-system-config.js

feat(progress-spinner)

---

src/lib/progress-spinner/progress-spinner.component.html
src/lib/progress-spinner/progress-spinner.component.spec.ts
src/lib/progress-spinner/progress-spinner.scss

Поправил работу в ie 11 и edge

fix(progress-spinner)_ie11_edge_fix

---

src/lib-dev/input/styles.scss
src/lib-dev/input/template.html
src/lib/form-field/form-field.scss
src/lib/form-field/form-field.ts

* исправлена ширина form-field'а (конечный размер зависит только от контейнера)
* исправлено отображение input'а с cleaner'ом (прыгающая ширина)

fix: corrected input's width

---

src/lib-dev/panel/template.html
src/lib-dev/typography/template.html
src/lib/core/styles/typography/_typography.scss

@Fost кроме изменений макетов, вот изменение в коде

Rename display-1 to display-3 and vice versa

---

src/lib/form-field/_form-field-theme.scss

fix disabled input

---

src/lib/timepicker/timepicker.spec.ts
src/lib/timepicker/timepicker.ts

При вставке из буфера времени вставленное добавляется к существующему вводу, а не заменяет его

fix(timepicker): Incorrect clipboard paste logic (#163477)

---

src/lib/timepicker/timepicker.ts

fix: При нажатии стрелками вверх-вниз видно как курсор кратковременно перескакивает в начало/конец инпута (#163476)

fix(timepicker): Noisy cursor movements on arrow keys (#163476)

---

src/lib-dev/tabs/styles.scss
src/lib-dev/tabs/template.html
src/lib/tabs/_tabs-common.scss
src/lib/tabs/_tabs-theme.scss
src/lib/tabs/tab-body.scss
src/lib/tabs/tab-group.html
src/lib/tabs/tab-group.scss
src/lib/tabs/tab-group.spec.ts
src/lib/tabs/tab-group.ts
src/lib/tabs/tab-header.html
src/lib/tabs/tab-header.scss
src/lib/tabs/tab-label-wrapper.ts
src/lib/tabs/tab-nav-bar/tab-nav-bar.scss
src/lib/tabs/tab-nav-bar/tab-nav-bar.spec.ts
src/lib/tabs/tab-nav-bar/tab-nav-bar.ts
src/lib/tabs/tab.html
src/lib/tabs/tab.ts

В целом по темной теме вроде все норм.
По коду там ппц, было желание очень многое переделать, но пока не судьба...

feat(dark-theme): Tabs (#169737)

---

src/lib/datepicker/_datepicker-theme.scss
src/lib/datepicker/calendar.scss
src/lib/datepicker/datepicker-toggle.scss

@Fost 
@lskramarov 
Root case:
some properties were set in incorrect place

fix:datepicker: incorrect theme styles using

---

src/dev-app/button/button-demo.html
src/lib-dev/all/template.html
src/lib-dev/button/template.html
src/lib-dev/dropdown/template.html
src/lib-dev/input/template.html
src/lib-dev/navbar/template.html
src/lib-dev/panel/template.html
src/lib/button-toggle/button-toggle.scss
src/lib/button/button.component.spec.ts
src/lib/button/button.component.ts
src/lib/button/button.module.ts
src/lib/datepicker/calendar-header.html
src/lib/datepicker/datepicker-toggle.html

McIconButton removed

---

docs/getting-started.md

updated getting-started, added mosaic-icons and moment-adapter to installation instructions
@Fost please take a look

feat(docs): UID-20 - updated getting-started doc

---

src/lib/button-toggle/button-toggle.component.ts

fix(button-toggle): button-toggle does not have type=button in button

---

packages/mosaic/datepicker/_datepicker-theme.scss

fix(datepicker): no calendar border

---

packages/mosaic/public-api.ts

@Fost , @lskramarov please take a look.

fix(popover): Popover missing public api export

---

packages/mosaic/form-field/_form-field-theme.scss

feat(form-field): formFieldWithoutBorder does not work in storybook

---

packages/cdk/tree/tree.ts
packages/mosaic-dev/tree-select/module.ts
packages/mosaic-dev/tree-select/template.html
packages/mosaic-dev/tree/module.ts
packages/mosaic-dev/tree/template.html
packages/mosaic/core/selection/pseudo-checkbox/pseudo-checkbox.ts
packages/mosaic/list/list-selection.component.spec.ts
packages/mosaic/list/list-selection.component.ts
packages/mosaic/select/select.component.ts
packages/mosaic/tree-select/tree-select.component.spec.ts
packages/mosaic/tree-select/tree-select.component.ts
packages/mosaic/tree-select/tree-select.html
packages/mosaic/tree/tree-option.ts
packages/mosaic/tree/tree-selection.ts

Тут сильно закостыленно.
Нужно создать тех долг на пару дней, что бы выпилить эти костыли и сделать нормально.

feat(tree): added ngModel

---

packages/mosaic-dev/tree/module.ts
packages/mosaic-dev/tree/template.html
packages/mosaic/tree-select/tree-select.component.ts
packages/mosaic/tree/tree-selection.ts

fix(tree): added emitting events for navigationChange and selectionChange #UIM-2

---

packages/mosaic/navbar/navbar.scss
yarn.lock

fix(navbar): navbar default paddings for first element

---

packages/mosaic-dev/sidebar/module.ts
packages/mosaic-dev/sidebar/template.html
packages/mosaic/splitter/_splitter-theme.scss
packages/mosaic/splitter/splitter.component.html
packages/mosaic/splitter/splitter.component.ts
packages/mosaic/splitter/splitter.scss

Поправил disabled состояние + немного почистил код.

fix(splitter): Задизейбленный сплиттер имеет неправильный стиль курсора #UIM-48

---

packages/mosaic-dev/modal/module.ts
packages/mosaic-dev/modal/template.html
packages/mosaic/modal/README.md
packages/mosaic/modal/modal.component.html
packages/mosaic/modal/modal.component.ts
packages/mosaic/modal/modal.directive.ts
packages/mosaic/modal/modal.module.ts
packages/mosaic/modal/modal.scss
packages/mosaic/modal/modal.service.ts
packages/mosaic/modal/modal.type.ts

+ Добавлен параметр { static: true } для ViewChild modalContainer

feat(modal): allow open instance of component into the dialog

---

packages/mosaic-dev/vertical-navbar/styles.scss
packages/mosaic/vertical-navbar/vertical-navbar.component.scss

feat(vertical-navbar): new default styles for vertical-navbar (#52)
new default styles for vertical-navbar (was moved from mosaic-dev)
Breaking Changes: none

feat(vertical-navbar): new default styles for vertical-navbar (#52)

---

packages/mosaic/splitter/_splitter-theme.scss
packages/mosaic/splitter/splitter.component.html
packages/mosaic/splitter/splitter.component.ts
packages/mosaic/splitter/splitter.scss

fix(splitter): splitter jumps (narrow size), if the block has a min-width (#UIM-49)

---

packages/mosaic-dev/all/module.ts
packages/mosaic-dev/all/template.html

Сюда же, исправление примера с выбором элементов в дереве.

fix(chore): in dev example tree select all nodes on click (#UIM-92)

---

packages/mosaic-dev/timepicker/module.ts
packages/mosaic-dev/timepicker/template.html
packages/mosaic-moment-adapter/adapter/moment-date-adapter.ts
packages/mosaic/timepicker/timepicker.ts

I did some refactoring after fix.
@RistiCore

fix(timepicker): need keep source date (#UIM-79)

---

packages/mosaic/checkbox/_checkbox-theme.scss
packages/mosaic/core/styles/_alerts.scss
packages/mosaic/list/_list-theme.scss
packages/mosaic/list/list-selection.component.ts
packages/mosaic/list/list.component.ts
packages/mosaic/navbar/_navbar-theme.scss

fix(list): fixing focus in list, checkbox and navbar 
FocusManager was added to list-selection component
Breaking Changes: none
Копия #94 PR

fix(list): fixing focus in list, checkbox and navbar 

---

packages/docs/src/_app-theme.scss
packages/docs/src/app/components/navbar/_navbar-theme.scss
packages/docs/src/app/components/navbar/navbar.component.ts
packages/docs/src/app/components/navbar/navbar.module.ts
packages/docs/src/app/components/navbar/navbar.scss
packages/docs/src/app/components/navbar/navbar.template.html
packages/docs/src/main.scss

Пока не сделано изменение активного цвета - сейчас он меняется при выборе темы. Шаблон и стили готовы, класс NavbarComponent еще пишу.

feat(docs): navbar styling

---

packages/docs/src/app/components/navbar/navbar.component.ts
packages/docs/src/app/components/navbar/navbar.scss
packages/docs/src/app/components/navbar/navbar.template.html

В компонент navbar документации добавлен выбор активного цвета

feat(docs): navbar color picker corrected

---

packages/mosaic-dev/splitter/template.html
packages/mosaic/splitter/_splitter-theme.scss
packages/mosaic/splitter/splitter.component.html
packages/mosaic/splitter/splitter.component.ts

Насчет:
> У сплиттеров должен быть ховер, оверлей как у элементов листа, например.
еще уточним, пока непонятен смысл.
Иконки пока убрал, быстро пробросить их из вне не так просто.

feat(splitter): changed styles and added some improvements (#UIM-83)

---

packages/docs/src/app/components/sidenav/sidenav.component.html
packages/docs/src/app/components/sidenav/sidenav.component.ts
packages/docs/src/app/components/sidenav/sidenav.scss

Добавлены стили для компонента документации sidenav.

feat(docs): sidenav styling

---

packages/docs/src/app/components/anchors/anchors.component.html
packages/docs/src/app/components/anchors/anchors.component.ts
packages/docs/src/app/components/anchors/anchors.module.ts
packages/docs/src/app/components/anchors/anchors.scss
packages/docs/src/app/components/main-layout/main-layout.component.html
packages/docs/src/app/components/main-layout/main-layout.component.scss
packages/docs/src/app/components/main-layout/main-layout.module.ts

Добавлено правое меню с якорями и поправлены стили в main-layout

feat(docs): anchors component was added

---

packages/mosaic/tree-select/tree-select.component.spec.ts
packages/mosaic/tree-select/tree-select.html

fix(tree-select): customization of the matcher does not work (UIM-116)

---

packages/mosaic/modal/modal.component.ts
packages/mosaic/modal/modal.spec.ts

When you open a modal window, a scroll-bar appears to the right

fix(modal): remove padding-right from body UIM-114

---

packages/mosaic/tree/tree-selection.ts

Убрал миксины.
+ сейчас CdkTree<any>, потом нужно сделать нормальный генерик,..

fix(tree): replacing mixins with methods (#UIM-129)

---

package.json
packages/mosaic-dev/formatters/demo-template.html
packages/mosaic-dev/formatters/formatters-template.html
packages/mosaic-dev/formatters/module.ts
packages/mosaic-dev/formatters/styles.scss
packages/mosaic/core/formatters/index.ts
packages/mosaic/core/formatters/number/formatter.ts
packages/mosaic/core/public-api.ts

@mikeozornin можно посмотреть.

feat(formatters): Added number formatter (McDecimalPipe) (#UIM-84)

---

404.html
packages/docs/src/app/components/main-layout/main-layout.component.ts

Для корректной работы роутинга в GitHub Pages необходимо создать файл 404.html (из PR) и поместить в корень сайта (https://positive-js.github.io/mosaic-previews/) - на него GitHub Pages будет вести при запросе несуществующих на сервере ссылок, а 404.html в свою очередь переадресует запрос на нужное приложение с route в get параметрах для ангуляра.

WIP feat(docs): routing in production

---

packages/mosaic-examples/checkbox-indeterminate/checkbox-indeterminate-example.css
packages/mosaic-examples/checkbox-indeterminate/checkbox-indeterminate-example.html
packages/mosaic-examples/checkbox-indeterminate/checkbox-indeterminate-example.ts
packages/mosaic-examples/checkbox-overview/checkbox-overview-example.html
packages/mosaic/checkbox/checkbox.md

Checkbox documentation and examples were updated.

feat(docs): checkbox documentation

---

packages/docs/src/styles/_markdown.scss

feat(docs): list styling

---

packages/docs/src/app/components/anchors/anchors.component.ts

Исправлено определение URL для корректной работы с base href

feat(docs): anchors are working with base href

---

packages/docs/src/app/shared/example-viewer/example-viewer.html
packages/docs/src/app/shared/example-viewer/example-viewer.scss
packages/docs/src/app/shared/example-viewer/example-viewer.ts

Задана минимальная высота редактора кода, убрана тень при показе кода целиком и скорректирована генерация номеров строк.

feat(docs): correcting example viewer

---

packages/cdk/tree/control/flat-tree-control.spec.ts
packages/cdk/tree/control/flat-tree-control.ts
packages/cdk/tree/control/tree-control.ts
packages/cdk/tree/nested-node.ts
packages/cdk/tree/toggle.ts
packages/cdk/tree/tree.ts
packages/mosaic-dev/tree-select/module.ts
packages/mosaic-dev/tree-select/template.html
packages/mosaic-dev/tree/module.ts
packages/mosaic-dev/tree/template.html
packages/mosaic/core/option/option.ts
packages/mosaic/list/list-selection.component.spec.ts
packages/mosaic/list/list-selection.component.ts
packages/mosaic/select/select.component.ts
packages/mosaic/select/select.html
packages/mosaic/tree-select/tree-select.component.spec.ts
packages/mosaic/tree-select/tree-select.component.ts
packages/mosaic/tree-select/tree-select.html
packages/mosaic/tree-select/tree-select.scss
packages/mosaic/tree/_tree-theme.scss
packages/mosaic/tree/toggle.ts
packages/mosaic/tree/tree-option.component.ts
packages/mosaic/tree/tree-selection.component.spec.ts
packages/mosaic/tree/tree-selection.component.ts

Видимо это будет долгая задача, небольшими порциями буду исправлять всю магию в дереве.

 refactor(tree, tree-select): technical debts + refactoring in tree and tree-select (#UIM-39)

---

packages/mosaic-dev/popover/template.html
packages/mosaic-dev/tooltip/styles.scss
packages/mosaic/tooltip/_tooltip-theme.scss
packages/mosaic/tooltip/tooltip.scss

@Fost , @lskramarov , @mikeozornin please take a look.
@mikeozornin  please note: arrow height and width were changed to match 16px width on template between two extreme points.

fix(tooltip): Edge styles fix, arrow styles update

---

packages/docs/src/app/shared/example-viewer/example-viewer.html
packages/docs/src/app/shared/example-viewer/example-viewer.scss
packages/docs/src/app/shared/example-viewer/example-viewer.ts
packages/docs/src/highlightjs/material-dark.scss
packages/docs/src/highlightjs/material-light.scss

Изменено поведение ссылки "Показать полностью". Теперь ссылка показывается только если длина кода превышает 10 строк.
Исправлен баг определения длины кода при первой загрузке редоктора.

feat(docs): show/hide editor fix WIP

---

packages/mosaic-dev/cdk-virtual-scroll-custom-strategy/module.ts
packages/mosaic-dev/cdk-virtual-scroll-data-source/module.ts
packages/mosaic/schematics/ng-add/fonts/roboto-fonts.ts
tools/release/base-release-task.ts

Исправлены ошибки magic numbers, 
отключена ошибка insecure-random у Math.random()

feat(cdk): tslint errors

---

packages/mosaic/radio/radio.component.ts
packages/mosaic/radio/radio.module.ts

fixing naming-convention, ordered-imports and member-ordering-advanced  tslint errors

chore(radio): fixing tslint errors

---

packages/mosaic/toggle/toggle.component.html
packages/mosaic/toggle/toggle.component.ts

Fixing naming-convention and member-ordering errors.

chore(toggle): fixing tslint errors

---

packages/docs/src/app/components/navbar/_navbar-theme.scss
packages/docs/src/app/components/navbar/navbar.scss
packages/docs/src/app/components/navbar/navbar.template.html

Из-за использования span внутри mc-button не срабатывал модификатор mc-icon_right, выпадающие списки переверстаны с учетом специфики компонента.

fix(docs): fixing dropdown trigger icon

---

packages/mosaic-dev/all/module.ts
packages/mosaic-dev/tree-select/module.ts
packages/mosaic-dev/tree/module.ts
packages/mosaic/select/select.component.ts
packages/mosaic/tree-select/tree-select.component.spec.ts
packages/mosaic/tree-select/tree-select.component.ts
packages/mosaic/tree-select/tree-select.html
packages/mosaic/tree/tree-option.component.ts
packages/mosaic/tree/tree-selection.component.ts

fix(tree): fixed few bugs (example, initial highlight, focus on close, autoselect=true)

---

packages/mosaic/progress-bar/progress-bar.component.spec.ts
packages/mosaic/progress-bar/progress-bar.component.ts
packages/mosaic/progress-spinner/progress-spinner.component.spec.ts
packages/mosaic/progress-spinner/progress-spinner.component.ts
packages/mosaic/select/select.component.spec.ts
packages/mosaic/sidebar/sidebar.spec.ts
packages/mosaic/splitter/splitter.module.ts
packages/mosaic/tags/tag-list.component.ts
packages/mosaic/tags/tag-remove.spec.ts
packages/mosaic/textarea/textarea.component.ts
packages/mosaic/timepicker/timepicker.constants.ts
packages/mosaic/timepicker/timepicker.ts
packages/mosaic/tree-select/tree-select.component.spec.ts
packages/mosaic/tree/node.directive.ts
packages/mosaic/tree/padding.directive.ts
packages/mosaic/vertical-navbar/vertical-navbar-item.component.ts
packages/mosaic/vertical-navbar/vertical-navbar.component.spec.ts

fixing mocha-no-side-effect-code, no-unnecessary-type-assertion, naming-convention, ordered-imports, no-magic-numbers, no-empty, orthodox-getter-and-setter tslint errors

chore(common): fixing tslint errors

---

packages/mosaic-dev/tree/module.ts
packages/mosaic-dev/tree/template.html
packages/mosaic/tree-select/tree-select.component.spec.ts
packages/mosaic/tree-select/tree-select.component.ts
packages/mosaic/tree/tree-option.component.ts
packages/mosaic/tree/tree-option.html
packages/mosaic/tree/tree-selection.component.spec.ts
packages/mosaic/tree/tree-selection.component.ts
yarn.lock

feat(tree): added selection via ctrl and shift (#197)

---

packages/mosaic-examples/mosaic/dropdown/dropdown-nested/dropdown-nested-example.css
packages/mosaic-examples/mosaic/dropdown/dropdown-nested/dropdown-nested-example.html
packages/mosaic-examples/mosaic/dropdown/dropdown-nested/dropdown-nested-example.ts
packages/mosaic-examples/mosaic/dropdown/dropdown-overview/dropdown-overview-example.css
packages/mosaic-examples/mosaic/dropdown/dropdown-overview/dropdown-overview-example.html
packages/mosaic-examples/mosaic/dropdown/dropdown-overview/dropdown-overview-example.ts
packages/mosaic-examples/mosaic/dropdown/module.ts
packages/mosaic/dropdown/dropdown.md

Dropdown overview and nested dropdown examples are added.

feat(docs): adding dropdown examples

---

packages/mosaic-dev/textarea/template.html
packages/mosaic/textarea/textarea.component.ts

feat(textarea): textarea does not support rows attribute (#UIM-239)

---

packages/docs/src/assets/stackblitz/mosaic-module.ts
packages/mosaic-examples/mosaic/datepicker/datepicker-disabled/datepicker-disabled-example.css
packages/mosaic-examples/mosaic/datepicker/datepicker-disabled/datepicker-disabled-example.html
packages/mosaic-examples/mosaic/datepicker/datepicker-disabled/datepicker-disabled-example.ts
packages/mosaic-examples/mosaic/datepicker/datepicker-overview/datepicker-overview-example.css
packages/mosaic-examples/mosaic/datepicker/datepicker-overview/datepicker-overview-example.html
packages/mosaic-examples/mosaic/datepicker/datepicker-overview/datepicker-overview-example.ts
packages/mosaic-examples/mosaic/datepicker/module.ts
packages/mosaic/datepicker/datepicker.md

Datepicker overview and disabled examples are added.

feat(docs): add datepicker examples

---

packages/mosaic-dev/tree-select/module.ts
packages/mosaic-dev/tree-select/template.html
packages/mosaic-dev/tree/template.html
packages/mosaic/select/select.component.ts
packages/mosaic/tree-select/tree-select.component.spec.ts
packages/mosaic/tree-select/tree-select.component.ts
packages/mosaic/tree/tree-option.component.ts
packages/mosaic/tree/tree-selection.component.ts

Много ченджей из-за того что заметил и пофиксил два бага:
- при открытии селекта выбирался элемент (из-за того что автоселект был включен по-умолчанию)
- при закрытом селекте выделялось более одного элемента и при открытии фокус не снимался с этих элементов

fix(tree): noUnselectLast does not work (#UIM-178)

---

packages/docs/src/assets/stackblitz/mosaic-module.ts
packages/mosaic-examples/mosaic/datepicker/datepicker-disabled/datepicker-disabled-example.ts
packages/mosaic-examples/mosaic/datepicker/datepicker-language/datepicker-language-example.css
packages/mosaic-examples/mosaic/datepicker/datepicker-language/datepicker-language-example.html
packages/mosaic-examples/mosaic/datepicker/datepicker-language/datepicker-language-example.ts
packages/mosaic-examples/mosaic/datepicker/datepicker-toggle/datepicker-toggle-example.css
packages/mosaic-examples/mosaic/datepicker/datepicker-toggle/datepicker-toggle-example.html
packages/mosaic-examples/mosaic/datepicker/datepicker-toggle/datepicker-toggle-example.ts
packages/mosaic-examples/mosaic/datepicker/datepicker-year/datepicker-year-example.css
packages/mosaic-examples/mosaic/datepicker/datepicker-year/datepicker-year-example.html
packages/mosaic-examples/mosaic/datepicker/datepicker-year/datepicker-year-example.ts
packages/mosaic-examples/mosaic/datepicker/module.ts
packages/mosaic/datepicker/datepicker.md

datepicker-language, datepicker-toggle and datepicker-year examples are added

feat(docs): adding datapicker examples

---

packages/mosaic/core/_core.scss
packages/mosaic/core/_misc.scss

fix(app): console warning - theme detection   (#UIM-168)

---

packages/docs/src/assets/stackblitz/mosaic-module.ts
packages/mosaic-examples/mosaic/progress-bar/module.ts
packages/mosaic-examples/mosaic/progress-bar/progress-bar-indeterminate/progress-bar-indeterminate-example.css
packages/mosaic-examples/mosaic/progress-bar/progress-bar-indeterminate/progress-bar-indeterminate-example.html
packages/mosaic-examples/mosaic/progress-bar/progress-bar-indeterminate/progress-bar-indeterminate-example.ts
packages/mosaic-examples/mosaic/progress-bar/progress-bar-overview/progress-bar-overview-example.css
packages/mosaic-examples/mosaic/progress-bar/progress-bar-overview/progress-bar-overview-example.html
packages/mosaic-examples/mosaic/progress-bar/progress-bar-overview/progress-bar-overview-example.ts
packages/mosaic/progress-bar/progress-bar.md
scripts/deploy/publish-docs-preview.ts

Indeterminate progress bar and  basic progress bar examples are added

feat(docs): adding progress bar examples

---

packages/docs/src/app/components/navbar/_navbar-theme.scss
packages/docs/src/app/shared/documentation-items/documentation-items.ts
packages/docs/src/app/shared/example-viewer/example-viewer.scss
packages/docs/src/main.scss
packages/mosaic-examples/mosaic/alerts/alerts-overview/alerts-overview-example.css
packages/mosaic-examples/mosaic/navbar/module.ts
packages/mosaic-examples/mosaic/navbar/navbar-overview/navbar-overview-example.css
packages/mosaic-examples/mosaic/navbar/navbar-overview/navbar-overview-example.html
packages/mosaic-examples/mosaic/navbar/navbar-overview/navbar-overview-example.ts
packages/mosaic-examples/mosaic/splitter/splitter-fixed/splitter-fixed-example.css
packages/mosaic-examples/mosaic/splitter/splitter-nested/splitter-nested-example.css
packages/mosaic-examples/mosaic/splitter/splitter-overview/splitter-overview-example.css
packages/mosaic-examples/mosaic/splitter/splitter-vertical/splitter-vertical-example.css
packages/mosaic-examples/mosaic/tabs/module.ts
packages/mosaic-examples/mosaic/tabs/tabs-light-overview/tabs-light-example.html
packages/mosaic-examples/mosaic/tabs/tabs-light-overview/tabs-light-example.ts
packages/mosaic-examples/mosaic/tabs/tabs-overview/tabs-overview-example.html
packages/mosaic-examples/mosaic/tabs/tabs-overview/tabs-overview-example.ts
packages/mosaic-examples/mosaic/tabs/tabs-stretch-overview/tabs-stretch-example.html
packages/mosaic-examples/mosaic/tabs/tabs-stretch-overview/tabs-stretch-example.ts
packages/mosaic/navbar/navbar.md
packages/mosaic/tabs/tabs.md
packages/mosaic/tags/tags-autocomplete.md
packages/mosaic/tags/tags-input.md
packages/mosaic/tags/tags-list.md
packages/mosaic/tags/tags.md

feat(docs): added navbar and tabs (#UIM-326)

---

packages/mosaic/core/styles/typography/_typography.scss
packages/mosaic/core/styles/typography/typography.md
tools/webpack/default_index.ejs

https://youtrack.ptsecurity.com/issue/UIM-330
Zeplin: https://zpl.io/bPm0L96

fix(typography): fix subheading font-weight(#UIM-330)

---

commitlint.config.js
packages/mosaic-moment-adapter/adapter/locales/en-US.ts
packages/mosaic-moment-adapter/adapter/locales/ru-RU.ts
packages/mosaic-moment-adapter/adapter/moment-date-adapter.spec.ts

Добавил для короткого и длинного форматов. @mikeozornin

feat(formatter): changed format for seconds (#UIM-285)

---

packages/mosaic/input/input.spec.ts
packages/mosaic/input/input.ts
packages/mosaic/input/stepperUtils.spec.ts
packages/mosaic/input/stepperUtils.ts

Как так вышло, что пришлось удалить немного кода...

fix(number): stepUp and stepDown are not work with empty value (#UIM-333)

---

packages/mosaic-dev/tooltip/template.html
packages/mosaic-examples/mosaic/tooltip/tooltip-overview/tooltip-overview-example.html

https://youtrack.ptsecurity.com/issue/UIM-347

fix(docs): tooltip example bold text

---

packages/mosaic-dev/all/template.html
packages/mosaic-dev/tree/template.html

Продолжение этого: https://github.com/positive-js/mosaic/pull/381

fix(docs): fix bold button text

---

packages/cdk/datetime/date-adapter.ts
packages/mosaic-moment-adapter/adapter/locales/IFormatterConfig.ts
packages/mosaic-moment-adapter/adapter/locales/en-US.ts
packages/mosaic-moment-adapter/adapter/locales/ru-RU.ts
packages/mosaic-moment-adapter/adapter/moment-date-adapter.spec.ts
packages/mosaic-moment-adapter/adapter/moment-date-adapter.ts

Добавил (перенес из первой мозайки) методы и форматы для "открытых" диапазонов.

fix(formatter): date-adapter does not have methods for open range (#UIM-163)

---

packages/mosaic-dev/dropdown/template.html
packages/mosaic/dropdown/_dropdown-theme.scss
packages/mosaic/dropdown/dropdown-content.ts
packages/mosaic/dropdown/dropdown-item.ts
packages/mosaic/dropdown/dropdown-trigger.ts
packages/mosaic/dropdown/dropdown.component.ts
packages/mosaic/dropdown/dropdown.html
packages/mosaic/dropdown/dropdown.scss

Помимо исправления самого бага нашлись мелкие недочеты + немного порефакторил.

fix(dropdown): disabled item should prevent click event (#UIM-315)

---

packages/mosaic-dev/dropdown/template.html
packages/mosaic/dropdown/_dropdown-theme.scss
packages/mosaic/dropdown/dropdown-content.ts
packages/mosaic/dropdown/dropdown-item.ts
packages/mosaic/dropdown/dropdown-trigger.ts
packages/mosaic/dropdown/dropdown.component.ts
packages/mosaic/dropdown/dropdown.html
packages/mosaic/dropdown/dropdown.scss

fix(dropdown): disabled item should prevent click event (#UIM-315) (#396)

---

commitlint.config.js
package.json
tools/release/changelog-commit-template.hbs
tools/release/changelog-root-template.hbs
tools/release/changelog.ts

доработки:
* теперь выводится shortHash коммита
* добавлен раздел Docs
* изменения в writeOpts
* добавлен список исключений для пакетов excludedChangelogPackages
* capitalize для title (имя пакета)

build: changelog format improvements

---

packages/docs/src/app/shared/example-viewer/example-viewer.html

Должно быть пунктирное, а не сплошное.

fix(docs): correct expand link underline

---

packages/cdk/a11y/aria-describer/aria-describer.spec.ts
packages/cdk/a11y/aria-describer/aria-describer.ts
packages/cdk/a11y/focus-monitor/focus-monitor.ts

tslint deprecation and naming-convention errors fix

chore(common): tslint fix

---

packages/mosaic-dev/theme-picker/theme-storage/theme-storage.spec.ts
packages/wallabyTest.ts
tools/dgeni/processors/merge-inherited-properties.ts
tools/example-module/parse-example-file.ts
tools/example-module/parse-example-module-file.ts
tools/gulp/tasks/lint.ts
tools/gulp/tasks/validate-licenses.ts
tools/highlight-files/highlight-code-block.ts
tools/packages/build-bundles.ts
tools/packages/build-package.ts
tools/packages/compile-entry-point.ts
tools/release/changelog.ts
tools/release/notify-release.ts
tools/release/prompt/new-version-prompt.ts
tools/release/prompt/prerelease-labels.ts
tools/release/publish-release.ts
tools/release/stage-release.ts

tslint magic numbers, restrict-plus-operands, ordered-import, await-promise, no-invalid-template-strings, no-unnecessary-type-assertion, no-unnecessary-callback-wrapper, mocha-no-side-effect-code rules are fixed

chore(common): fixing tslint

---

packages/cdk/tree/tree._spec.ts
packages/docs/src/app/components/component-viewer/component-viewer.component.ts

combineLatest syntax deprication: https://github.com/ReactiveX/rxjs/pull/4641

chore(common): fixing combineLatest syntax deprication

---

packages/mosaic/form-field/form-field.ts
packages/mosaic/tags/tag-input.ts
packages/mosaic/tags/tag-list.component.ts
packages/mosaic/tags/tag-text-control.ts

Сделал проброс ошибок через statusChanges, думаю возможен и другой вариант через иерархию контролов, но что то с первой раза не взлетело...

fix(tags): input validation in tags-list (#UIM-368)

---

.circleci/config.yml

lint_mosaic job is added to .circleci/config.yml for TSLint check

build: adding tslint check

---

packages/mosaic-dev/validation/module.ts
packages/mosaic-dev/validation/styles.scss
packages/mosaic-dev/validation/template.html
packages/mosaic/core/validation/validation.ts
packages/mosaic/input/input.spec.ts
packages/mosaic/input/input.ts

Так же добавил несколько тестов на валидацию и создал задачу на тесты, что бы покрыть все кейсы нашей валидации (UIM-379)

fix(input): input emits unexpected valueChanges (#UIM-366)

---

package.json
yarn.lock

YAML pre-commit check on changed files is added with the use of lint-staged and pre-commit packages.
If a mistake is found git will show:

build: adding yaml pre-commit check

---

packages/mosaic-dev/validation/module.ts
packages/mosaic-dev/validation/template.html
packages/mosaic/core/validation/validation.ts
packages/mosaic/input/input.ts

fix(input): errors in console after loading form with mc-validation (#UIM-376)

---

packages/mosaic-dev/popover/module.ts
packages/mosaic-dev/popover/template.html
packages/mosaic/popover/popover.component.ts

fix(popover): mcVisibleChange emits only after hidding popover (#UIM-386)

---

packages/mosaic-dev/validation/template.html
packages/mosaic/tags/tag-list.component.ts

fix(tags): fixed error "Expression has changed after it was checked" (#UIM-376)

---

packages/mosaic-dev/popover/module.ts
packages/mosaic-dev/popover/styles.scss
packages/mosaic-dev/popover/template.html
packages/mosaic/popover/popover.scss

@Fost @lskramarov 
Убрал important у классов стилей + поправил запуск демо по поповеру.

fix(popover): Popover max width update, fixing start issue (UIM-424)

---

packages/mosaic/core/styles/functions/_number.scss

Fix https://sonarcloud.io/project/issues?id=positive-js_mosaic&issues=AXDJZUm-HxoWp8206Z90&open=AXDJZUm-HxoWp8206Z90

fix: remove unit pica

---

package.json
packages/mosaic/form-field/cleaner.ts
packages/mosaic/package.json
yarn.lock

feat(input): replace cleaner icon #UIM-442

---

package.json

Small typing error in package.json

(fix): fix package json mistype

---

packages/mosaic/datepicker/_datepicker-theme.scss

There was added point for class "mc-calendar__body-cell-content"

fix(datepicker): set point for class mc-calendar__body-cell-content

---

packages/mosaic/select/select.component.ts

fix(select): select lose selected element after selection with search (#UIM-475)

---

packages/mosaic-dev/tooltip/module.ts
packages/mosaic-dev/tooltip/template.html
packages/mosaic/tooltip/tooltip.component.html
packages/mosaic/tooltip/tooltip.component.ts
packages/mosaic/tooltip/tooltip.scss

@Fost 
Please take a look.
mcTitle was not reacting on outer value update.
Dev-example updated.

fix(tooltip): Title does not react on value change (#UIM-482)

---

packages/mosaic-dev/toggle/module.ts
packages/mosaic-dev/toggle/template.html
packages/mosaic/toggle/toggle.component.html
packages/mosaic/toggle/toggle.component.ts

fix(toggle): Each click on the toggle emits two events instead of one #UIM-476

---

packages/mosaic-dev/tags/module.ts
packages/mosaic-dev/tags/template.html

fix(tags): tags are incorrectly added to mc-tag-list with autocomplete #UIM-486

---

packages/mosaic/timepicker/timepicker.ts

fix(timepicker): Incorrect validation behavior (#UIM-485)

---

packages/mosaic/dropdown/dropdown-trigger.ts
packages/mosaic/dropdown/dropdown.component.ts
packages/mosaic/dropdown/dropdown.spec.ts

По умолчанию здесь выключен backdrop и добавлена обработка события для закрытия.
Если я правильно понял, хотели именно такое поведение. Насчет того что бы оно было включено по умолчанию не уверен, посмотри пожалуйста.

feat(dropdown): by default backdrop disabled (#UIM-531)

---

packages/mosaic/popover/popover.component.ts

feat(popover): by default backdrop disabled and added parameter for it (#UIM-538)

---

packages/mosaic/datepicker/datepicker.spec.ts
packages/mosaic/datepicker/datepicker.ts

feat(datepicker): by default backdrop disabled and added parameter for it (#UIM-539)

---

packages/mosaic-dev/tags/template.html

fix(docs): Autocomplete with copy & paste (#UIM-540)

---

packages/mosaic-examples/mosaic/validation/validation-composite/validation-composite-example.css
packages/mosaic-examples/mosaic/validation/validation-composite/validation-composite-example.html
packages/mosaic-examples/mosaic/validation/validation-composite/validation-composite-example.ts
packages/mosaic-examples/mosaic/validation/validation-global/validation-global-example.css
packages/mosaic-examples/mosaic/validation/validation-global/validation-global-example.html
packages/mosaic-examples/mosaic/validation/validation-global/validation-global-example.ts
packages/mosaic-examples/mosaic/validation/validation-on-blur/validation-on-blur-example.css
packages/mosaic-examples/mosaic/validation/validation-on-blur/validation-on-blur-example.html
packages/mosaic-examples/mosaic/validation/validation-on-blur/validation-on-blur-example.ts
packages/mosaic-examples/mosaic/validation/validation-on-type/validation-on-type-example.css
packages/mosaic-examples/mosaic/validation/validation-on-type/validation-on-type-example.html
packages/mosaic-examples/mosaic/validation/validation-on-type/validation-on-type-example.ts
packages/mosaic-examples/mosaic/validation/validation-overview/validation-overview-example.css
packages/mosaic-examples/mosaic/validation/validation-overview/validation-overview-example.html
packages/mosaic-examples/mosaic/validation/validation-overview/validation-overview-example.ts
packages/mosaic-examples/mosaic/validation/validation-small/validation-small-example.css
packages/mosaic-examples/mosaic/validation/validation-small/validation-small-example.html
packages/mosaic-examples/mosaic/validation/validation-small/validation-small-example.ts
packages/mosaic/tooltip/_tooltip-theme.scss

Обновил доки по новым макетам.

fix(docs): updated after getting sketch (#UIM-543)

---

packages/mosaic/form-field/form-field.ts

* @lskramarov 
* @Fost 
Observables unsubscribed

fix(form-field): Unsubscribe in the form field (#UIM-553)

---

packages/cdk/datetime/date-adapter.ts
packages/mosaic-dev/date-formatter/module.ts
packages/mosaic-dev/date-formatter/template.html
packages/mosaic-examples/mosaic/date-formatter/absolute-date-formatter/absolute-date-formatter-example.html
packages/mosaic-examples/mosaic/date-formatter/absolute-date-formatter/absolute-date-formatter-example.ts
packages/mosaic-moment-adapter/adapter/locales/en-US.ts
packages/mosaic-moment-adapter/adapter/locales/ru-RU.ts
packages/mosaic-moment-adapter/adapter/moment-date-adapter.spec.ts
packages/mosaic-moment-adapter/adapter/moment-date-adapter.ts

feat(date-adapter): added milliseconds and microseconds for absolute dates (#UIM-446)

---

package.json
yarn.lock

Удалена неиспользуемая typescript-tslint-plugin

fix: removed unused typescript-tslint-plugin

---

packages/mosaic/tooltip/tooltip.component.ts

Pass a number value to the tooltip.

fix(tooltip): added type number (#UIM-557)

---

packages/mosaic-examples/mosaic/button/button-overview/button-overview-example.css

В доках размер кнопки зависит от размера чекбокса

fix(docs): Size dependence on the checkbox (#UIM-432)

---

packages/mosaic-moment-adapter/adapter/locales/ru-RU.ts
packages/mosaic-moment-adapter/adapter/moment-date-adapter.spec.ts

В русском языке месяц от года отделялся запятой
Задача: [https://youtrack.ptsecurity.com/issue/UIM-454](url)

fix(formatter): Date-formatter comma (#UIM-454)

---

packages/mosaic-examples/mosaic/select/select-multiple-overview/select-multiple-overview-example.html

Задача: [https://youtrack.ptsecurity.com/issue/UIM-580](url)

fix(docs): added mc-cleaner (#UIM-580)

---

packages/mosaic/select/select.html
packages/mosaic/select/select.scss

Исправление неправильного поведения multiple select.
Комментарии задачи: https://youtrack.ptsecurity.com/issue/UIM-580

fix(select): fixed multiple selection hidden items (#UIM-580)

---

packages/mosaic/dropdown/dropdown-trigger.ts
packages/mosaic/dropdown/dropdown.component.ts
packages/mosaic/dropdown/dropdown.spec.ts

Задача: https://youtrack.ptsecurity.com/issue/UIM-564

fix(dropdown): focus on opening (UIM-564)

---

packages/mosaic/popover/popover.scss

Задача: https://youtrack.ptsecurity.com/issue/UIM-625

fix(popover): fixed displaying arrow (#UIM-625)

---

packages/docs/src/app/components/navbar/navbar.component.ts
packages/docs/src/app/components/navbar/navbar.template.html
packages/mosaic/dropdown/dropdown.scss

Задача: https://youtrack.ptsecurity.com/issue/UIM-624

fix(docs): fixed version switch (#UIM-624)

---

package.json
tools/gulp/utils/build-scss-pipeline.ts
yarn.lock

tech(build): updated npm minor libs

---

packages/mosaic-dev/popover/template.html
packages/mosaic/core/pop-up/pop-up-trigger.ts
packages/mosaic/popover/popover.component.ts
packages/mosaic/popover/popover.spec.ts
packages/mosaic/tooltip/tooltip.component.ts

fix(popover): change name mcPopover[Visible | Placement | PlacementPriority | PlacementChange | VisibleChange] (#UIM-811)

---

packages/mosaic/splitter/spliltter.spec.ts
packages/mosaic/splitter/splitter.component.ts

Добавлена индикация когда размер области сплитера изменился

fix(splitter): sizeChange callback for McSplitterAreaDirective (#UIM-755)

---

packages/mosaic/tags/tag.component.ts
packages/mosaic/tags/tag.scss

[Tags: нет отступа в tag без иконки внутри](https://youtrack.ptsecurity.com/issue/UIM-761)
Добавлен отступ, если нет иконки

fix(modal): tag without icon (#UIM-761)

---

packages/docs/src/app/components/component-viewer/component-viewer.component.ts
packages/mosaic/core/formatters/date/formatter.spec.ts
packages/mosaic/core/formatters/date/formatter.ts
packages/mosaic/dropdown/_dropdown-theme.scss
packages/mosaic/dropdown/dropdown-item.component.ts
packages/mosaic/dropdown/dropdown-item.html
packages/mosaic/dropdown/dropdown-item.scss
packages/mosaic/dropdown/dropdown.spec.ts

[Добавить названия страниц во вкладки браузера](https://youtrack.ptsecurity.com/issue/UIM-747)
Добавлено название 
MS Edge:
Google Chrome:
Firefox:

feat(docs): title with label (#UIM-747)

---

packages/docs/src/styles/default-theme/_variables.scss
packages/docs/src/styles/default-theme/css-tokens.css
packages/docs/src/styles/default-theme/tokens.ts
packages/docs/src/styles/green-theme/_variables.scss
packages/docs/src/styles/green-theme/css-tokens.css
packages/docs/src/styles/green-theme/tokens.ts
packages/docs/src/styles/red-theme/_variables.scss
packages/docs/src/styles/red-theme/css-tokens.css
packages/docs/src/styles/red-theme/tokens.ts
packages/docs/src/styles/yellow-theme/_variables.scss
packages/docs/src/styles/yellow-theme/css-tokens.css
packages/docs/src/styles/yellow-theme/tokens.ts
packages/mosaic/core/formatters/date/formatter.spec.ts
packages/mosaic/core/formatters/date/formatter.ts
packages/mosaic/design-tokens/_variables.scss
packages/mosaic/design-tokens/css-tokens.css
packages/mosaic/design-tokens/style-dictionary/build.js
packages/mosaic/design-tokens/style-dictionary/configs/index.js
packages/mosaic/design-tokens/tokens.ts
packages/mosaic/dropdown/_dropdown-theme.scss
packages/mosaic/dropdown/dropdown-item.component.ts
packages/mosaic/dropdown/dropdown-item.html
packages/mosaic/dropdown/dropdown-item.scss
packages/mosaic/dropdown/dropdown.spec.ts

[Убрать дату генерации файла в токенах](https://youtrack.ptsecurity.com/issue/UIM-731)
Добавлена опция `fileHeader`
Взято [отсюда](https://amzn.github.io/style-dictionary/#/formats?id=file-headers)

fix(common): configure comment in token-files (#UIM-731)

---

packages/docs/src/app/components/anchors/anchors.scss
packages/docs/src/app/components/footer/footer.component.scss
packages/docs/src/app/components/main-layout/main-layout.component.scss
packages/docs/src/app/components/navbar/navbar.scss
packages/docs/src/app/components/sidenav/sidenav.scss

Лэйаут списком для доков при маленьком экране

feat(docs): layout for small screen (#UIM-831)

---

packages/mosaic/dropdown/dropdown-trigger.directive.ts

[Dropdown в главном меню не реагирует на нажатие пробела](https://youtrack.ptsecurity.com/issue/UIM-674)
Pressing enter/spase not always  trigger  the click handler

fix(dropdown): press space by dropdown (#UIM-674)

---

packages/mosaic/datepicker/datepicker-input.directive.ts

https://youtrack.ptsecurity.com/issue/UIM-733

feat(datepicker): cut 5 digit year (#UIM-733)

---

packages/mosaic-luxon-adapter/adapter/date-adapter.spec.ts
packages/mosaic-luxon-adapter/adapter/date-adapter.ts
packages/mosaic/datepicker/datepicker-input.directive.ts

[Datepicker: при вводе с клавиатуры даты 31.09 - ошибка в консоли](https://youtrack.ptsecurity.com/issue/UIM-738)

fix(datepicker): fix datepicker for value '31.09.2021' and etc (#UIM-738)

---

packages/mosaic/button/_button-base.scss

https://youtrack.ptsecurity.com/issue/UIM-740

feat(button): remove button margin in safari (#UIM-740)

---

packages/mosaic-dev/splitter/styles.scss
packages/mosaic-dev/splitter/template.html
packages/mosaic/splitter/_splitter-theme.scss
packages/mosaic/splitter/spliltter.spec.ts
packages/mosaic/splitter/splitter.component.html
packages/mosaic/splitter/splitter.component.ts
packages/mosaic/splitter/splitter.module.ts
packages/mosaic/splitter/splitter.scss

Добавлен режим "призрака" для желоба между областями, чтобы ресайз происходил только при его отпускании

feat(splitter): ghost mode (UIM-115)

---

packages/mosaic-examples/mosaic/tree-select/index.ts
packages/mosaic-examples/mosaic/tree-select/tree-select-lazyload/tree-select-lazyload-example.css
packages/mosaic-examples/mosaic/tree-select/tree-select-lazyload/tree-select-lazyload-example.html
packages/mosaic-examples/mosaic/tree-select/tree-select-lazyload/tree-select-lazyload-example.ts
packages/mosaic-examples/mosaic/tree/index.ts
packages/mosaic-examples/mosaic/tree/tree-lazyload/tree-lazyload-example.css
packages/mosaic-examples/mosaic/tree/tree-lazyload/tree-lazyload-example.html
packages/mosaic-examples/mosaic/tree/tree-lazyload/tree-lazyload-example.ts
packages/mosaic/tree-select/tree-select.md
packages/mosaic/tree/data-source/flat-data-source.ts
packages/mosaic/tree/tree-option.component.ts
packages/mosaic/tree/tree-option.html
packages/mosaic/tree/tree-option.scss
packages/mosaic/tree/tree.md
tools/public_api_guard/mosaic/tree.api.md

Копия https://github.com/positive-js/mosaic/pull/775, для того что бы собрались доки и можно было проверить примеры, ибо локально у меня не работает.

fix(docs): add example lazy loading options (#UIM-802)

---

packages/mosaic/form-field/cleaner.ts

https://youtrack.ptsecurity.com/issue/UIM-852

fix(input): change cleaner color (#UIM-852)

---

packages/mosaic/tags/tag.component.ts

У меня только так получилось исправить проблему с запуском Storybook.
Подняла объявление директивы McTagRemove и добавила Inject через forwardRef

fix(tags): remove circular dependencies (#UIM-872)
